name: Unit tests
on: [workflow_call]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Test project
        run: yarn test
