name: Master Pipeline

on:
  push:
    branches:
      - master

jobs:

  test:
    needs: setup
    uses: ./.github/workflows/master-pipe-tests.yml

  deploy:
    needs: test
    uses: ./.github/workflows/master-pipe-deploy.yml
