name: Master Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    uses: ./.github/workflows/master-pipe-setup.yml

  test:
    needs: setup
    uses: ./.github/workflows/master-pipe-tests.yml

  deploy:
    needs: test
    uses: ./.github/workflows/master-pipe-deploy.yml
